### ISSUE TITLE
Could not find member 'debug' on object of type 'AuctionResponse'. Path 'debug', line 1, position 9

### ISSUE THREAD

**Issue by D4NNY1000000** [trydis/FIFA-Ultimate-Team-Toolkit#176]
Had an auction search working the other day but doesn't seem to work now.  

My code:
```c#
var searchParameters = new PlayerSearchParameters {
   Page = 1,
   Level = Level.Silver,
   League = League.BarclaysPremierLeague,
   Nation = Nation.Scotland,
   Position = Position.LeftWingBack,
   Team = Team.Watford,
   MaxBid = maxBid,
   MaxBuy = 750
};

var searchResponse = await client.SearchAsync(searchParameters);
AuctionInfo auctionInfo = searchResponse.AuctionInfo[0];
await client.PlaceBidAsync(auctionInfo, auctionInfo.BuyNowPrice);
```
No JSON result and this error.
```
{"Could not find member 'debug' on object of type 'AuctionResponse'. Path 'debug', line 1, position 9."}

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at UltimateTeam.Toolkit.Requests.FutRequestBase.<Deserialize>d__22`1.MoveNext()
```
The post:
POST /ut/game/fifa16/transfermarket?start=0&num=13&leag=13&lev=silver&nat=42&team=1795&maxb=750&macr=7999999&pos=LWB&type=player HTTP/1.1

The JSON:
JSON
code=500
debug=
reason=
string=

So seems path isnt working now?

**Comment by sipahis** [comment]
InternalServerError. You send to many requests.

**Comment by D4NNY1000000** [comment]
How many is too many?
I was using a new account, could it be that im not allowed on the transfer market yet with this account?

**Comment by D4NNY1000000** [comment]
Same issue as #164. I was using a newly created account and had not played the required amount of matches to unlock access to transfer market, therefore the error was occurring.
