### ISSUE TITLE
GetItemAsync(auctionInfo) 404

### ISSUE THREAD

**Issue by D4NNY1000000** [trydis/FIFA-Ultimate-Team-Toolkit#177]
Does this work anymore?  Keep getting a 404 status.
{"Response status code does not indicate success: 404 (Not Found)."}

GET /fifa/fltOnlineAssets/B488919F-23B5-497F-9FC0-CACFB38863D0/2016/fut/items/web/-2147314548.json HTTP/1.1

**Comment by A-VORONKIN** [comment]
I have error Bad request when I`m trying to search anything.

**Comment by bbday** [comment]
it is a problem about resourceId cause is negative number, must be update CalculateBaseId() function

**Comment by D4NNY1000000** [comment]
I was using the example in the readme.txt but it didnt seem to calculate properly.
I switched to auctionInfo.itemData.assetId and this had been working but a got a legend and his data didnt appear in my table.
```C#
Newtonsoft.Json.JsonSerializationException was unhandled by user code
  HResult=-2146233088
  Message=Could not find member 'LegendsBio' on object of type 'Item'. Path 'Item.LegendsBio', line 1, position 382.
  Source=UltimateTeam.Toolkit
  StackTrace:
       at UltimateTeam.Toolkit.Requests.FutRequestBase.<Deserialize>d__22`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at UltimateTeam.Toolkit.Requests.ItemRequest.<PerformRequestAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by D4NNY1000000** [comment]
Fixed in my version.  Create 3 new classes and add the LegendsBio attribute to the Item class.
```C#
        public LegendsBio LegendsBio { get; set; }
```
```C#
using System.Collections.Generic;

namespace UltimateTeam.Toolkit.Models
{
    public class LegendsBio
    {
        public List<ClubCareer> ClubCareer { get; set; }
        public List<NationalCareer> NationalCareer { get; set; }
    }
}
```
```C#
namespace UltimateTeam.Toolkit.Models
{
    public class ClubCareer
    {
        public string StartYear { get; set; }
        public string EndYear { get; set; }
        public string TeamId { get; set; }
        public string Matches { get; set; }
        public string Goals { get; set; }
    }
}
```
```C#
namespace UltimateTeam.Toolkit.Models
{
    public class NationalCareer
    {
        public string StartYear { get; set; }
        public string EndYear { get; set; }
        public string TeamId { get; set; }
        public string Matches { get; set; }
        public string Goals { get; set; }
    }
}
```

**Comment by bbday** [comment]
better way set json report error false

JsonSerializerSettings = new JsonSerializerSettings { MissingMemberHandling = MissingMemberHandling.Ignore };

when call playeritem

**Comment by D4NNY1000000** [comment]
Does the calculatebaseid function work?

**Comment by omrihaviv** [comment]
Why is this change not pushed? Some are not getting this error when calling GetItemAsync?

**Comment by bbday** [comment]
Because is a problem only for some item "LegendsBio" i think is only for special player (Xbox ?)
